import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.21"

    // Apply the application plugin to add support for building a CLI application in Java.
    application

//    java
    groovy
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = URI("https://jitpack.io") }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")

    // Use the Kotlin test library.
//    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

//    testImplementation("org.codehaus.groovy:groovy-all:3.0.8")
//    testImplementation("org.spockframework.spock:spock-core:spock-2.3")
    // https://mvnrepository.com/artifact/org.spockframework/spock-core
    testImplementation("org.spockframework:spock-core:2.3-groovy-3.0")
    testImplementation("org.codehaus.groovy:groovy-sql:3.0.13")
    testImplementation("com.h2database:h2:2.1.214")
}

application {
    // Define the main class for the application.
    mainClass.set("spocktest.AppKt")
}

tasks.withType<Test> {
    useJUnitPlatform()
}
